import tempfile
import os
from storage_connection import S3Provider, CernboxProvider

def test_s3():
    print("--- Testing AWS S3 connection ---")
    try:
        s3 = S3Provider(bucket="digitization-dev")
        base_path = "cern-archives/raw/PDF/"
        
        folders = s3.list_folders(base_path)
        print("✅ Read: Success! Connected to S3.")
        print(f"Found {len(folders)} folders in '{base_path}'.")
        
        print("\n--- Testing S3 Upload ---")
        remote_test_file = f"{base_path}upload_test_s3.txt"
        
        with tempfile.NamedTemporaryFile(delete=False, mode='w', encoding='utf-8') as tmp:
            tmp.write("Upload test file generated by test_connections.py")
            tmp_path = tmp.name
            
        try:
            s3.upload_file(tmp_path, remote_test_file)
            print(f"✅ Write: Success! File sent to: {remote_test_file}")
        finally:
            os.remove(tmp_path) 
            
    except Exception as e:
        print(f"❌ Failed to connect/operate on S3.")
        print(f"Details: {e}")

def test_cernbox():
    print("\n--- Testing CERNBOX connection (Hybrid Mode) ---")
    
    # 1. Read Variables (Public)
    public_hash = "QslvWRIPsBcDAOK"
    read_base_path = "" # Relative path inside the public link
    
    # 2. Write Variables (Private/Authenticated)
    cern_user = "" # CERN username
    cern_password = os.environ.get("CERNBOX_PASSWORD")
    write_base_path = ""#"eos/user/{u}/{user}/teste/"
    
    if public_hash == "PUT_YOUR_PUBLIC_HASH_HERE":
        print("Warning: Configure the public_hash in the code before testing.")
        return
        
    if not cern_password:
        print("❌ The CERNBOX_PASSWORD environment variable is not set.")
        print("Run in terminal: export CERNBOX_PASSWORD='your_password'")
        return

    try:
        # Passing all three arguments
        cernbox = CernboxProvider(public_link_hash=public_hash, account=cern_user, password=cern_password)
        
        print("\n[Phase 1: Reading from Public Link]")
        folders = cernbox.list_folders(read_base_path)
        print("✅ Read: Success (Anonymous)!")
        print(f"Found {len(folders)} items at the root of the link.")
        
        print("\n[Phase 2: Writing via Authenticated WebDAV]")
        remote_test_file = f"{write_base_path}hybrid_connection_test.txt"
        
        with tempfile.NamedTemporaryFile(delete=False, mode='w', encoding='utf-8') as tmp:
            tmp.write("Authenticated upload from test_connections.py")
            tmp_path = tmp.name
            
        try:
            cernbox.upload_file(tmp_path, remote_test_file)
            print(f"✅ Write: Success (Authenticated)! File sent to: {remote_test_file}")
        finally:
            os.remove(tmp_path)
            
    except Exception as e:
        print(f"❌ Failed to connect/operate on CERNBOX.")
        print(f"Details: {e}")

if __name__ == "__main__":
    # test_s3()
    test_cernbox()