name: Build Images

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    name: Image build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: registry.cern.ch
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          registry: registry.cern.ch
          push: true
          tags: registry.cern.ch/cern-sis/digitization:latest,registry.cern.ch/cern-sis/digitization:${{ github.sha }}

      - name: Build and push with tag
        id: docker_build_tag
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'release'}}
        with:
          registry: registry.cern.ch
          push: true
          tags: registry.cern.ch/cern-sis/digitization:${{ github.ref_name }}

      - name: Deploy QA
        uses: peter-evans/repository-dispatch@v1
        if: ${{ github.event_name == 'push' || github.event_name == 'release'}}
        with:
          token: ${{ secrets.INSPIRE_BOT_TOKEN }}
          repository: cern-sis/kubernetes
          event-type: deploy
          client-payload: '{"project": "digitization", "environment": "qa", "application": "digitization", "namespace": "digitization-qa","image":"registry.cern.ch/cern-sis/digitization","new_tag":"${{ github.sha }}"}'

      - name: Deploy PROD
        uses: peter-evans/repository-dispatch@v1
        if: ${{ github.event_name == 'release'}}
        with:
          token: ${{ secrets.INSPIRE_BOT_TOKEN }}
          repository: cern-sis/kubernetes
          event-type: deploy
          client-payload: '{"project": "digitization", "environment": "prod", "application": "digitization", "namespace": "digitization-prod","image":"registry.cern.ch/cern-sis/digitization","new_tag": "${{ github.ref_name }}" }'
