name: Build Images

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    name: Image build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push
        id: build
        uses: cern-sis/gh-workflows/.github/actions/docker-build@v5.6.0
        with:
          registry: registry.cern.ch
          image: cern-sis/digitization
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          cache: false

      - name: Deploy QA
        if: ${{ github.event_name == 'push'}}
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v5.6.0
        with:
          event-type: update
          images: ${{ steps.build.outputs.image-tags }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}

      - name: Deploy PROD
        if: ${{ github.event_name == 'release'}}
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v5.6.0
        with:
          event-type: release
          images: ${{ steps.build.outputs.image-tags }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}
